from selenium.webdriver.common.by import By
xpath = By.XPATH
css_selector = By.CSS_SELECTOR

flight_way_radio_btn = (xpath, "//input[@value='{}']")
open_flight_input = (xpath, "//p[@title='{}']")
flight_input = (xpath, "//input[@id='input-with-icon-adornment']")
select_city_option = (xpath, "(//span[contains(text(),'{}')])[1]")
date_calendar = (xpath, "(//div[@aria-label='{}'])[{}]")
date_input = (xpath, "//div[contains(@aria-label,'{}')]")
traveller_class_input = (xpath, "//input[@id='drop-down-input']")
traveller_filter = (xpath, "//div[@aria-label='Travellers class inputbox']")
select_traveller_option = (xpath, "//p[@aria-label='{}']/parent::div//descendant::li[{}]")
apply_traveller_btn = (xpath, "//button[normalize-space()='Done']")
search_flights_button = (xpath, "//button[normalize-space()='Search']")
sorting_options = (xpath, "//div[@class='grid section-sort']")
prices_on_different_days = (xpath, "//div[@class='scroller full-width flex']")
depart_details_section = (xpath, "(//div[contains(@class,'depart-details')])[1]")
arrival_details_section = (xpath, "(//div[contains(@class,'arrival-details text-right')])[1]")
search_results_section = (css_selector, "div.flightItem.border-shadow.pr")
calendar_next_button = (xpath, "(//button[@aria-label='Next Month'])[2]")
calendar_prev_button = (xpath, "(//button[contains(@aria-label,'Previous Month')])[1]")
round_trip_sorting_by_price = (xpath, "//ul[@role='tablist']/li")
round_trip_details_section = (xpath, "(//div[@class='flight-det table full-width clearfix'])[6]")
no_of_flights = (xpath, "//article[@ng-controller='scheduleController']/descendant::div[@class='flight-det table full-width clearfix']")
more_filters = (xpath, "//span[text()='More Filters ']")
price_slider = (xpath, "//div[@class='rangeslider rangeslider-horizontal']")
price_slider_handle = (xpath, "//div[@class='rangeslider__handle']")
target_price_elem = (xpath, "//p[contains(@class,'font-lightgrey text-left')]/span[2]")
depart_time_range = (xpath, "//div[contains(@class,'tabs')]//label[2]") #6AM - 12PM
select_flight = (xpath, "(//div[contains(@class,'airlines-list text-left')])[1]//label//span[text()='{}']")
apply_filter_btn = (xpath, "//input[contains(@value,'Apply Filters')]")
min_price_elem = (xpath, "//li[@class='rangeslider__label-item'][2]")
max_price_elem = (xpath, "//li[@class='rangeslider__label-item'][1]")
filter_no_flight_msg = (xpath, "//span[@class='ellipsis font-red i-b']")
filter_with_flight = (xpath, "(//span[contains(@class,'i-b')][normalize-space()='Air India'])[1]")
start_departure_date = (xpath, "//span[contains(text(),'Start')]")
add_another_city_btn = (xpath, "//button[normalize-space()='+ Add Another City']")
multi_city_results_section = (xpath, "//div[contains(@class,'legselector')]//ul[contains(@class,'full-width no-wrap ovf-hidden mob-calendar')]//li")
multi_city_search_btn = (xpath, "(//button[contains(@type,'button')][normalize-space()='Search'])[1]")
same_city_search = (css_selector, "#simple-toast-message div p")
no_flight_found = (xpath, "//section[@id='Flight-APP']/descendant::p[2]")
input_invalid_city = (xpath, "//h2[normalize-space()='No match found for the search']")