from selenium.webdriver.common.by import By
xpath = By.XPATH
css_selector = By.CSS_SELECTOR

open_hotel_city = (css_selector, "button[aria-label='Button']")
hotel_city_input = (css_selector, "input[type='text']")
select_hotel_city_list_item = (xpath, "(//ul[contains(@class, 'SearchList_listing')])[1]/descendant::p[normalize-space()='{}']")
select_hotel_city_list_dd_container = (xpath, "//div[contains(@class, 'SearchPanelModal_searchList')]")
open_date_calendar = (xpath, "//div[contains(@class, 'SearchPanel_hotelDetails')]//button[{}]")
select_date_in_calendar = (xpath, "//div[@aria-label='{}']")
calendar_next_btn = (xpath, "(//button//img[@alt='Night Icon'])[4]")
calendar_prev_btn = (xpath, "(//button//img[@alt='Night Icon'])[1]")
search_hotels_button = (css_selector, "button[aria-label='Search']")
hotel_search_results_section = (xpath, "//div[contains(@class, 'HotelList_hotelListingHeader')]//p")
filters_side_panel = (xpath, "//div[contains(@class,'HotelList_filterSection')]")
star_5_rating_filter_option = (css_selector, "button#st-chipCheckbox-5")
hotel_filter_option = (xpath, "//label[normalize-space()='{}']")
search_result_breadcrumb = (xpath, "//nav[@aria-label='breadcrumb']/descendant::li[2]//a")
localities_show_more_btn = (xpath, "(//div[contains(@class,'Accordion_accordion__KatAh')])[4]/descendant::button[contains(@class, 'ShowMore_buttonLink')][text()='Show more']")
applied_filters_section = (xpath, "//p[text()='Applied Filters']/following-sibling::div[contains(@class,'ComboChips_chipCombobox')]//button//span")
checkout_more_than_15_days_error_message = (xpath, "//span[contains(text(),'{0}')]")
invalid_city_search_with_empty_list = (xpath, "//div[contains(@class,'SearchPanelModal_searchList')]")
open_room_and_guests_btn = (xpath, "//div[contains(@class,'SearchPanel_roomDetails')]")
room_and_guests_popup = (xpath, "//div[contains(@class,'SearchPanel_roomWrapper')]")
select_adults = (xpath, "(//button[contains(@aria-label,'{}')])[{}]")
add_room_button = (xpath, "//button[normalize-space()='Add Room']")
apply_room_and_guest_button = (xpath, "//button[normalize-space()='Apply']")
selected_room_and_guests_info = (xpath, "//div[contains(@class,'SearchPanel_roomDetails')]/descendant::div[contains(@class,'SearchInputField_searchRegionInfo')]//p")